== Arsitektur Perangkat Lunak

> Good architecture makes the system easy to understand, easy to develop, easy to maintain, and easy
> to deploy. The ultimate goal is to minimize the lifetime cost of the system and to maximize
> programmer productivity. - Robert C Martin

Arsitektur Perangkat Lunak adalah pemahaman bersama tentang desain sebuah sistem. Arsitektur
perangkat lunak menunjukkan penempatan kode di lapisan atau level abstraksi tertentu.

=== Arsitektur 3 tingkat, MVC, Lasagna

Arsitektur 3 tingkat atau __three-tier architecture__ adalah arsitektur yang umum dipakai. Kita
memisahkan lapisan untuk menampilkan (__view__), logika (__logic/controller__), dan penyimpanan
(__storage/model__).

[.float-group]
--
[.left]
.Arsitektur Tiga Tingkat
image::three-tier-arch.svg[3TierArch,450]

Arsitektur ini sangat sederhana dan mudah dipahami. Masalah dari arsitektur ini adalah:
arsitektur ini tidak __spesifik__. Perangkat lunak apapun bisa mengklaim punya arsitektur seperti
ini.

Masalah kedua adalah, tiap lapisan dari arsitektur, **tidak bisa dideploy** secara independen. Untuk
tim yang relatif kecil atau tidak memerlukan __independent deployability__, arsitektur ini cocok
karena mudah dipahami dan koordinasi antar tim bisa dilakukan dengan cepat. Untuk sebuah
organisasi berkembang dan mempunyai __domain__ yang berkembang dan banyak, arsitektur ini akan
merepotkan karena untuk merilis satu fitur, ketiga lapisannya harus diubah, dan bisa jadi
perubahannya perlu koordinasi dengan tim lain. 
--

=== Onion / Heksagonal

Arsitektur __Onion__ atau __Heksagonal__ sedikit berbeda dengan arsitektur tiga tingakt. Arsitektur
tiga tingkat mengklaim bahwa dependensi paling ujung adalah lapisan penyimpanan atau __storage__.
Arsitektur onion dan heksagonal menempatkan __domain__ sebagai lapisan terdalam. Arsitektur ini yang
akan kita pakai di keseluruhan modul training ini.

Bentuk arsitektur onion ini banyak sekali. Robert C Martin (Uncle Bob) mendesain apa yang dia sebut
dengan __Clean Architecture__. Alistair Cockburn dengan __Hexagonal Architecture__.

.Heksagonal dan Onion
image::hexonion.svg[HexaGoninon, 900]

Dalam arsitektur heksagonal atau __onion__ seperti di atas, lapisan terdalam tidak ada pengetahuan
apapun atas lapisan terluarnya. Yang kita kerjakan di <<Dasar Rekayasa Perangkat Lunak>> adalah inti
dari arsitektur ini, yaitu di lapisan entitas, atau sering disebut lapisan domain atau __domain
layer__. Domain layer ini biasanya hanya berupa entitas dan objek saja dan tidak ada konteks maupun
pengetahuan terhadap penyimpanan maupun protokol jaringan.

[NOTE]
.Mengenai jumlah lapisan
====
Jumlah lapisan bisa juga lebih dari yang di gambar. Begitu pula mungkin saja beberapa lapisan
digabungkan atau ditambahkan.
====

=== Lapisan penyimpanan

Lapisan penyimpanan ini adalah lapisan yang menjembatani transfer data dari penyimpanan dan __domain
layer__. Lapisan ini bisa mencari dan menyimpan entitas yang sudah didefinisikan di __domain
layer__. __Pattern__ yang biasa dipakai adalah
https://martinfowler.com/eaaCatalog/repository.html[__Repository Pattern__]. Pola (__pattern__)
memisahkan domain dan kode untuk mengambil entitas berdasarkan kriteria atau predikat tertentu.

Umumnya sebuah __repository__ harus:

. Bisa mencari entitas berdasar kriteria tertentu, misalnya __ID__.
. Bisa menyimpan entitas secara keseluruhan.

==== Implementasi Lapisan Penyimpanan

Selanjutnya, kita akan mengimplementasikan lapisan penyimpanan dengan membuat __in memory store__
atau penyimpanan yang hanya akan menyimpan di dalam memori. Alasan saya memakai ini adalah untuk
menunjukkan bahwa lapisan penyimpanan bisa apa saja, termasuk memori, tidak harus basis data.

[source,go]
.memstore.go
----
type MemStore struct {
}
----

=== Latihan

