== Lapisan Use Case dan Infrastruktur

> Playing football is very simple, but playing simple football is the hardest thing there is. --
> Johan Cruyff

=== Lapisan __Use Case__

Lapisan __use case__ adalah lapisan yang berisi **logika bisnis spesifik untuk aplikasi tersebut**.
Lapisan ini yang mengatur aliran data dari dan ke entitas. Perubahan lapisan ini seharusnya tidak
mempengaruhi lapisan domain. Lapisan ini juga tidak mengerti dan bergantung tentang UI atau
__framework__ apapun. 

Dari training awal di Bab 2, kita sudah punya __story__ sebagai berikut:

[cols="1,2,5,8"]
.**User Stories** untuk aplikasi blog
|===
| No |Sebagai | saya ingin | sehingga

| 1
| Penulis
| menambahkan artikel baru
| artikel tersebut bisa dibaca oleh pembaca

| 2
| Penulis
| menyunting artikel saya
| artikel yang baru bisa dibaca oleh pembaca

| 3
| Pembaca
| melihat judul semua artikel yang ada
| saya bisa memilih artikel mana yang mau dibaca

| 4
| Pembaca 
| memilih satu artikel
| saya bisa membaca satu artikel tersebut

|===

Kita akan mengimplementasikan __story-story__ tersebut satu-persatu. Pada story nomor 1, kita sudah
mengimplementasikan operasi pembuatan artikel di domain layer. Sekarang kita akan mengintegrasikan
lapisan penyimpanan dan domain untuk mencapai satu __use case__ yang tertera dalam __story__ di
atas.

Todo: data flow

Kita akan buat __prototype__ dari __Use Case__ pertama. Karena kita tidak peduli implementasi detil
dari lapisan penyimpanan kita, yang kita inginkan hanya **operasinya**. Kita definisikan dua
__interface__ yaitu `ArticleFinder` untuk mencari artikel `ArticleSaver` untuk menyimpan artikel.
Isi dari methodnya kita salin saja.

[source,go,linenums]
.article_use_case.go
----
type ArticleFinder interface { // <1>
  FindArticleByID(ctx context.Context, id uuid.UUID) (Article, error) {
}

type ArticleSaver interface { // <2>
  SaveArticle(ctx context.Context, article Article) error
}

type ArticleFinderSaver interface { // <3>
  ArticleFinder
  ArticleSaver
}

type ArticleUseCase struct { <4>
  store ArticleFinderSaver
}

var ErrNilStore = errors.NewError("store cannot be nil")

func NewArticleUseCase(store ArticleFinderSaver) (*ArticleUseCase, error) { <5>
  if store == nil {
    return nil, ErrNilStore
  }

  return &ArticleUseCase{store: store}, nil
}
----
<1> __Interface__ untuk `ArticleFinder`, apapun yang bisa 'mencari' artikel.
<2> __Interface__ untuk `ArticleSaver`, apapun yang bisa 'menyimpan' artikel.
<3> __Interface__ gabungan untuk memudahkan implementasi penyimpanan yang mengimplementasikan
semuanya.
<4> Deklarasi __Use Case__ di mana dia mengandung `store` yang mengimplementasikan
`ArticleFinderSaver`. Use Case tidak perlu tau bentuk penyimpananannya seperti apa.
<5> Konstruktor untuk membuat objek use case yang akan mengecek valid tidaknya `store`.

Alasan dari pembagian beberapa __interface__ sekaligus adalah supaya kita bisa membagi implementasi
untuk operasi baca dan tulis di lapisan penyimpanan yang berbeda. Misal ditulis di RDBMS dan dibaca
lewat ElasticSearch.

[source,go,linenums]
.article_use_case.go
----
func (uc *ArticleUseCase) CreateArticle(ctx context.Context, title, content string) (Article, error) {
  newArticle, err := CreateArticle(title, content) // <1>

  if err != nil {
    return Article{}, err
  }

  err = uc.store.SaveArticle(ctx, newArticle) // <2>

  if err != nil {
    return Article{}, err
  }

  return newArticle, nil // <3>
}
----
<1> Buat artikel baru 
<2> Lalu Simpan
<3> Hanya kembalikan artikel jika berhasil.

Dan kita akan menulis kode pengujian untuk use case pertama. Input dan output yang kita uji kebetulan sama dengan
kasus pembuatan article. Perbedaannya di sini kita sudah melibatkan `MemStore`. Kondisi yang kita
uji adalah sebagai berikut:

[Example]
====
. Jika judul atau konten tidak valid keluarkan galat.
. Hanya buat jika judul dan kontennya valid.
====

Syarat untuk kasus nomor dua sama dengan syarat di lapisan domain, jadi kita tidak perlu menambahkan
aturan baru lagi.

[source,go,linenums]
.article_use_case_test.go
----
func TestCreateArticleUseCase(t *testing.T) {
	ctx := context.Background()
	mem := CreateMemStore()

	uc, err := NewArticleUseCase(mem)
	require.NoError(t, err)

	// tabel test
	tests := []struct {
		// nama test
		Name string
		// input
		Title   string
		Content string
		// output
		Err error
	}{
		{"EmptyTitleContent", "", "", ErrEmptyTitle},
		{"EmptyTitleOnly", "", validContent, ErrEmptyTitle},
		{"EmptyContent", validTitle, "", ErrEmptyContent},
		{"ShortTitle", "short", validContent, ErrTitleTooShort},
		{"ShortContent", validTitle, "short", ErrContentTooShort},
		{"TooLongTitle", longTitle, validContent, ErrTitleTooLong},
		{"ValidArticle", validTitle, validContent, nil},
	}

	// Test dijalankan satu-satu dari tabel
	for _, item := range tests {
		t.Run(item.Name, func(t *testing.T) {
			article, err := uc.CreateArticle(ctx, item.Title, item.Content)
			assert.Equal(t, item.Err, err)

			if err != nil {
				assert.True(t, article.IsNil())
				return
			}

			result, err := mem.FindArticleByID(ctx, article.ID)

			if assert.NoError(t, err) {
				assert.Equal(t, article, result)
			}
		})
	}
}
----

Untuk __story__ no 2, kita implementasikan sebagai method baru di use case. Kali ini kita coba
tuliskan pengujiannya terlebih dahulu. Di sini kita uji kasus-kasus sebagai berikut:

[Example]
====
. Jika id nya tidak ada, maka keluarkan galat.
. Jika judul dan konten tidak valid, keluarkan galat.
. Hanya mengganti jika judul dan konten valid. 
====

[source,go,linenums,highlight="50-55"]
.article_use_case_test.go
----
func TestEditArticleUseCase(t *testing.T) {
	ctx := context.Background()
	mem := CreateMemStore()

	a, err := CreateArticle(validTitle, validContent)
	require.NoError(t, err)

	mem.FillArticle(a)

	uc, err := NewArticleUseCase(mem)
	require.NoError(t, err)

	existID := a.ID
	nonExistentID := uuid.MustParse("30339469-935b-4ab5-8816-d8a47450fe5f")

	replaceContent := validContent[20:]
	// tabel test
	tests := []struct {
		// nama test
		Name string
		// input
		ID      uuid.UUID
		Title   string
		Content string
		// output
		Err error
	}{
		{"NonExistentID", nonExistentID, validTitle, replaceContent, ErrArticleNotFound},
		{"EmptyTitleContent", existID, "", "", ErrEmptyTitle},
		{"EmptyTitleOnly", existID, "", validContent, ErrEmptyTitle},
		{"EmptyContent", existID, validTitle, "", ErrEmptyContent},
		{"ShortTitle", existID, "short", validContent, ErrTitleTooShort},
		{"ShortContent", existID, validTitle, "short", ErrContentTooShort},
		{"TooLongTitle", existID, longTitle, validContent, ErrTitleTooLong},
		{"ValidArticle", existID, validTitle, replaceContent, nil},
	}

	// Test dijalankan satu-satu dari tabel
	for _, item := range tests {
		t.Run(item.Name, func(t *testing.T) {
			err := uc.EditArticle(ctx, item.ID, item.Title, item.Content)
			assert.Equal(t, item.Err, err)

			if err != nil {
				return
			}

			a, err := mem.FindArticleByID(ctx, item.ID)

			if !assert.NoError(t, err) {
				return
			}

			assert.Equal(t, item.Title, a.Title)
			assert.Equal(t, item.Content, a.Content)
		})
	}
}
----

Lalu kita implementasikan metode `EditArticle`  

[source,go,linenums]
.article_use_case.go
----
func (uc *ArticleUseCase) EditArticle(ctx context.Context, id uuid.UUID, newTitle, newContent string) error {
	article, err := uc.store.FindArticleByID(ctx, id) // <1>
	if err != nil {
		return err
	}

	if err = article.EditArticle(newTitle, newContent); err != nil { // <2>
		return err
	}

	return uc.store.SaveArticle(ctx, article) // <3>
}
----
<1> Baca artikel dari lapisan penyimpanan yang mengimplementasikan `ArticleFinder`.
<2> Eksekusi mutasi dari lapisan domain.
<3> Simpan perubahan artikel ke lapisan penyimpanan yang mengimplementasikan `ArticleSaver`.

=== Lapisan Aplikasi / Infrastruktur / __Framework__

Lapisan ini adalah lapisan yang berhubungan dengan dunia luar. Di sinilah protokol seperti HTTP dan
gRPC dipakai. Lapisan ini membungkus lapisan __use case__ supaya bisa diakses oleh dunia luar.
Lapisani ini biasanya kodenya agak sedikit banyak.

Contoh yang dilakukan di lapisan ini antara lain 

- Memproses dan menanggapi __request__ dan __response__ HTML.
- Mensanitasi __input__ dari pengguna.
- Serialisasi dan Deserialisasi (JSON, biner, gob, dan lain-lain)

Untuk mengimplementasi lapisan ini, kita akan memakai `net/http` dan
https://go-chi.io/[`chi`,window=_blank], pustaka untuk keperluan __routing__ dan __middleware__.
Sebelum mengimplementasikan saya akan membuat __scaffolding__ untuk keperluan ini. __Scaffolding__
ini akan berisi sebagai berikut:

. Sebuah struktur yang mewakili HTTP dan REST server. Saya akan namai `HTTPServer`. Struktur
ini akan berisi objek use case dan metode-metode untuk menangani __request__ dan __response__ HTTP.
. Sebuah fungsi `main` yang akan menjalankan server tersebut. Fungsi ini akan menyiapkan
routing, logging, dan middleware yang akan dipakai oleh keseluruhan program.

[source,go,linenums]
.server.go
----
package main

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5" //<1>
	"github.com/go-chi/chi/v5/middleware"
)

type HTTPServer struct { //<2>
	port uint16
	host string

	router *chi.Mux
}

func NewHTTPServer(options ...func(*HTTPServer) error) (*HTTPServer, error) { // <3>
	r := chi.NewRouter()

	r.Use(middleware.Logger) // <4>
	r.Use(middleware.Recoverer)

	httpServer := &HTTPServer{
		host:   "127.0.0.1",
		port:   8000,
		router: r,
	}

	if len(options) == 0 {
		return httpServer, nil
	}

	for _, opt := range options { <5>
		if err := opt(httpServer); err != nil {
			return nil, err
		}
	}

	return httpServer, nil
}

func (s *HTTPServer) Start() {
	listen := fmt.Sprintf("%s:%d", s.host, s.port)

	http.ListenAndServe(listen, s.router)
}

----
<1> Impor `chi` dan middlewarenya ke dalam program.
<2> HTTP server isinya hanya `host` `port` dan `router`.
<3> Fungsi untuk membuat objek `HTTPServer` dengan
https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis[__functional options__]
supaya kita punya __default__.
<4> Middleware yang kita pakai, `Logger` untuk menampilkan request dan response, `Recoverer` untuk
mengatasi jika ada `panic`
<5> Eksekusi __functional options__ jika ada.
<6> Main program di sini kita jalankan objek `HTTPServer` tadi.

Dan sebuah fungsi `main` yang isinya cukup pendek.

[source,go,linenums]
.main.go
----
func main() {
	server, err := NewHTTPServer()

	if err != nil {
		log.Fatal(err)
	}
  
  
  log.Printf("Server dijalankan di %s port %d ...", server.host, server.port)
	server.Start()
}
----

Sebelum kita lanjutkan, kita coba jalankan dulu dengan `go run`.

[source]
----
> go run .

2021/09/04 23:55:53 Server dijalankan di 127.0.0.1 port 8000 ...

----

Dan kita coba tes dengan menggunakan https://curl.haxx.se[curl] di window/tab yang lain.

[source]
----
> curl -v 127.0.0.1:8000 

*   Trying 127.0.0.1:8000...
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> GET / HTTP/1.1 <1>
> Host: 127.0.0.1:8000
> User-Agent: curl/7.78.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found <2>
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Sat, 04 Sep 2021 16:57:19 GMT
< Content-Length: 19
<
404 page not found <3>
* Connection #0 to host 127.0.0.1 left intact
----
<1> __Request__ yang dikirim.
<2> __Response__ yang didapat.
<3> __Body__ dari __response__ yang dikembalikan server.

==== Menyiapkan __Handler__ dan __Use Case__

Di sub bagian ini kita akan menggabungkan seluruh lapisan yang kita sudah buat sebelumnya menjadi
sebuah REST API. Kita akan mengimplementasikan HTTP handler sebagai berikut

[cols="2,1,5"]
.REST __Endpoint__ untuk dua __use case__
|===
| Path | Metode | Deskripsi 

.2+| `/articles`

| `POST` 
| Membuat satu artikel baru 

| `PUT` 
| Mengedit satu artikel 

|===

Kita tambahkan dulu lapisan __use case__ ke dalam `HTTPServer`

[source,go]
----
type HTTPServer struct {
  // tambahkan use case ke sini
  uc *ArticleUseCase 
  // ...
}

func NewHTTPServer(options ... func(*HTTPServer) error) (*HTTPServer, error){
  memStore := CreateMemStore()
  uc, err := NewArticleUseCase(memStore)

  if err != nil {
    return nil, err 
  }

  // ... lalu assign ke dalam httpServer
  
  httpServer := &HTTPServer {
    uc: uc,
    // ...
  }
}
----

Kita setuju baik untuk __payload__ maupun __response__ keduanya akan memakai format JSON, termasuk
dengan galat. Supaya mudah untuk mengirimkan galat sebagai response, kita membuat fungsi yang akan
membungkus galat sebagai JSON.

[source,go,linenums]
----
func writeError(w http.ResponseWriter, status int, err error) {
	w.WriteHeader(status)
	wrapper := struct {
		Message string `json:"message"`
	}{Message: err.Error()}
	json.NewEncoder(w).Encode(wrapper)
}
----

Dengan ini kita bisa menuliskan dua metode yang nantinya akan menangani request dan response untuk
kedua use case tadi.

[source,go,linenums]
----
func (s *HTTPServer) NewArticleHandler(w http.ResponseWriter, r *http.Request) {
	writeError(w, http.StatusNotImplemented, ErrNotImplemented)
}

func (s *HTTPServer) EditArticleHandler(w http.ResponseWriter, r *http.Request) {
	writeError(w, http.StatusNotImplemented, ErrNotImplemented)
}
----

Untuk memudahkan membuat route, kita akan buat sebuah fungsi utilitas `setupRoute` di `HTTPServer`
yang nantinya akan dipanggil di `NewHTTPServer` setelah konstruksi strukturnya.

[source,go,linenums]
----
func (s *HTTPServer) setupRoute() { // <1>
  r := s.router 

  r.Post("/articles", s.NewArticleHandler)
  r.Put("/articles/{articleID}", s.EditArticleHandler) <2>
}


func NewHTTPServer(options ...func(*HTTPServer) error) (*HTTPServer, error) {
	// ...

  httpServer := &HTTPServer{
		host:   "127.0.0.1",
		port:   8000,
		router: r,
		uc:     uc,
	}

	httpServer.setupRoute() // <2>

  // ...
}
----
<1> Definisi fungsi utilitas untuk men-setup route.
<2> `{articleID}` adalah path parameter yang akan di-__parse__ oleh chi nanti.
<3> Dipanggil di sini

Dan jika kita jalankan dengan `curl` ke __path__ `/articles` hasilnya kurang lebih sebagai berikut:

[source]
----
> curl -XPOST -v 127.0.0.1:8000/articles

*   Trying 127.0.0.1:8000...
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> POST /articles HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.78.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 501 Not Implemented <1>
< Date: Sat, 04 Sep 2021 17:25:44 GMT
< Content-Length: 41
< Content-Type: text/plain; charset=utf-8
<
{"message":"method not yet implemented"} <2>
----
<1> HTTP Status
<2> Galat yang sudah dibungkus dan menghasilkan JSON

==== Mengimplementasikan dan menguji HTTP __Handler__

[WARNING]
====
Implementasi yang ada di sini tidak memikirkan soal keamanan. Validasi yang ada hanya untuk
memastikan tidak ada __state__ yang invalid dan. Keamanan dan sanitasi __input__ akan dibahas di Bab
selanjutnya. Jangan menggunakan kode yang ada di sini untuk kepentingan __production__.
====

Kita implementasikan pembuatan artikel. Pembuatan artikel ini mempunyai spesifikasi sebagai berikut.
Semua __request__ dan __response__ menggunakan `content-type` : `application/json`.

[cols="1,1,3,1,3"]
.Spesifikasi endpoint
|===
| __Path__ | Metode HTTP | Contoh Payload 2+| Respons 

.5+| `/articles`
.5+| `POST`
.5+a| [source,json]
----
{
 "title": "ini judul sebuah artikel", 
 "content":"lorem ipsum dolor sit amit-amit"
}
----
| `201 Created`
a| [source,json] 
----
{
  "id": "b0632224-bf79-471e-8f86-cd4ec5e30432",
  "created_at": "2020-04-03T08:58:26Z"
}
----

| `400 Bad Request`
.3+a| [source,json]
----
{
    "message": "error-message-is-here"
}
----
| `500 Internal Server Error`
| `501 Not Implemented`
|===

Kita akan mendefinisikan struktur yang akan menampung __request__ dan __response__ langsung di dalam
handler.

[source,go,linenums,highlight="21"]
----
func wrapError(err error) []byte { // <1>
	wrapper := struct {
		Message string `json:"message"`
	}{Message: err.Error()}

	j, _ := json.Marshal(wrapper)

	return j
}

func writeError(w http.ResponseWriter, status int, err error) { // <2>
	w.WriteHeader(status)
	w.Header().Add("content-type", "application/json")
	w.Write(wrapError(err))
}

func (s *HTTPServer) NewArticleHandler(w http.ResponseWriter, r *http.Request) {
	var payload struct { // <3>
		Title   string `json:"title"`
		Content string `json:"content"`
	}
	ctx := r.Context()

	err := json.NewDecoder(r.Body).Decode(&payload)

	if err != nil {
		writeError(w, http.StatusBadRequest, ErrInvalidRequestPayload)
		return
	}

	article, err := s.uc.CreateArticle(ctx, payload.Title, payload.Content) // <4>

	if err != nil {
		writeError(w, http.StatusUnprocessableEntity, err)
		return
	}

	result := struct { // <5>
		ID        string `json:"id"`
		CreatedAt string `json:"created_at"`
	}{article.ID.String(), article.CreatedAt.Format(time.RFC3339)}

	writeJSON(w, http.StatusCreated, result)
}
----
<1> Fungsi utilitas untuk membungkus `error` menjadi tipe JSON.
<2> Fungsi utilitas untuk menulis JSON ke __response__.
<3> __Payload__ yang kita terima dari __request__.
<4> Jalankan __behaviour__ dari Use Case.
<5> Kembalikan hanya hasil yang berupa side effect.

==== Menguji __Handler__

Sebelum kita jalankan servernya, kita perlu membuat pengujian. Di dalam `net/http` dalam Go sudah
ada __package__ `httptest` sehingga kita bisa menguji input dan output dari handler ini.

Pertama-tama kita definisikan terlebih dahulu tabel ujinya dan beberapa fungsi utilitas untuk
menghasilkan nilai ekspektasinya.

[source,go,linenums]
----
func mustMarshalJSON(v interface{}) []byte { // <1>
	b, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return b
}

var ( // <2>
	invalidReqPayloadErrJSON = wrapError(ErrInvalidRequestPayload)
	emptyTitleErrJSON        = wrapError(ErrEmptyTitle)
	titleTooShortErrJSON     = wrapError(ErrTitleTooShort)
	contentTooShortErrJSON   = wrapError(ErrContentTooShort)
	titleTooLongErrJSON      = wrapError(ErrTitleTooLong)
)
----
<1> Fungsi utilitas untuk memudahkan menguji, akan `panic` jika tidak bisa dijadikan JSON.
<2> Variabel untuk mencocokkan hasil keluaran yang berupa `error`.

Kemudian kita definisikan tabel pengujiannya.

[source,go,linenums]
----
func TestCreateArticleHandler(t *testing.T) {
	type testPayload struct { <1>
		Title   string `json:"title"`
		Content string `json:"content"`
	}

	validPayload := testPayload{validTitle, validContent} <2>
	validPayloadJSON := mustMarshalJSON(validPayload)
	validArticle, _ := CreateArticle(validTitle, validContent)
	validArticleJSON := mustMarshalJSON(validArticle)

	tests := []struct { <3>
		name    string
		reqJSON []byte

		status int
		ret    []byte
	}{
		{"NilRequest", nil,
			http.StatusBadRequest, invalidReqPayloadErrJSON},
		{"BlankRequest", []byte(""),
			http.StatusBadRequest, invalidReqPayloadErrJSON},
		{"BlankJSONRequest", []byte("{}"),
			http.StatusUnprocessableEntity, emptyTitleErrJSON},
		{"WithoutMatchingKeys", []byte(`{"red":"yes"}`),
			http.StatusUnprocessableEntity, emptyTitleErrJSON},
		{"NilTitleAndContent", []byte(`{"title":nil,"content":nil}`),
			http.StatusUnprocessableEntity, emptyTitleErrJSON},
		{"ShortTitle", mustMarshalJSON(testPayload{"short", validContent}),
			http.StatusUnprocessableEntity, titleTooShortErrJSON},
		{"ShortContent", mustMarshalJSON(testPayload{validTitle, "short"}),
			http.StatusUnprocessableEntity, contentTooShortErrJSON},
		{"LongTitle", mustMarshalJSON(testPayload{longTitle, validContent}),
			http.StatusUnprocessableEntity, titleTooLongErrJSON},
		{"ValidArticle", validPayloadJSON,
			http.StatusCreated, validArticleJSON},
	}	
  // ... cuplikan kode selanjutnya setelah ini
}
----
<1> Struktur sementara untuk mengekspresikan __payload__ yang akan dikirimkan ke server.
<2> Beberapa variabel utilitas yang berisi __payload__ yang valid dan artikel yang valid.
<3> Tabel pengujian.

Lalu kita jalankan satu-satu pengujiannya dengan menggunakan __package__ `httptest`. __Package__
`httptest` mensimulasikan __request__ dan __response__ HTTP yang akan ditangani oleh handler
tertentu. Langkah-langkah pengujiannya terlihat dalam kode sebagai berikut:

[source,go,linenums]
----

	s, err := NewHTTPServer() // <1> 
	require.NoError(t, err)


	for _, item := range tests {
		t.Run(item.name, func(t *testing.T) {
			req := httptest.NewRequest(http.MethodPost, "/articles", 
				bytes.NewReader(item.reqJSON)) // <2>
			req.Header.Set("content-type", "application/json")
			rr := httptest.NewRecorder()

			s.NewArticleHandler(rr, req) // <3>

			res := rr.Result()
			defer res.Body.Close()

			assert.Equal(t, item.status, res.StatusCode) // <4>

			var buf bytes.Buffer
			n, err := buf.ReadFrom(res.Body)
			require.NoError(t, err)
			assert.NotZero(t, n)

			isErrorCode := res.StatusCode/100 > 3 // <5>

			if isErrorCode {
				assert.JSONEq(t, string(item.ret), buf.String())
				return
			}
      
      var ret struct {
				ID        string `json:"id"`
				CreatedAt string `json:"created_at"`
			}

			err = json.NewDecoder(&buf).Decode(&ret)

			if !assert.NoError(t, err) {
				return
			}

			_, err = uuid.Parse(ret.ID) // <6>
			assert.NoError(t, err)
			d, err := time.Parse(time.RFC3339, ret.CreatedAt)
			assert.NoError(t, err)
			assert.GreaterOrEqual(t, 4*time.Minute, time.Now().Sub(d)) // <7>
		})
	}
----
<1> Pembuatan objek `HTTPServer` yang akan diuji.
<2> Persiapan `httptest` dengan membuat `request` dan `recorder`.
<3> Eksekusi handler dengan `recorder` sebagai implementasi `http.ResponseWriter`.
<4> Uji dan bandingkan status dan kembaliannya.
<5> Uji untuk status dengan galat (4xx 5xx)
<6> Cek apakah ID nya valid atau tidak.
<7> Cek kalau artikelnya dibuat tidak lebih dari 5 menit yang lalu.


Setelah kita tulis, kita jalankan kode pengujiannya

[source]
----
> go test -run -v TestCreateArticleHandler .

=== RUN   TestCreateArticleHandler
=== RUN   TestCreateArticleHandler/NilRequest
=== RUN   TestCreateArticleHandler/BlankRequest
=== RUN   TestCreateArticleHandler/BlankJSONRequest
=== RUN   TestCreateArticleHandler/WithoutMatchingKeys
=== RUN   TestCreateArticleHandler/NilTitleAndContent
=== RUN   TestCreateArticleHandler/ShortTitle
=== RUN   TestCreateArticleHandler/ShortContent
=== RUN   TestCreateArticleHandler/LongTitle
=== RUN   TestCreateArticleHandler/ValidArticle
--- PASS: TestCreateArticleHandler (0.00s)
    --- PASS: TestCreateArticleHandler/NilRequest (0.00s)
    --- PASS: TestCreateArticleHandler/BlankRequest (0.00s)
    --- PASS: TestCreateArticleHandler/BlankJSONRequest (0.00s)
    --- PASS: TestCreateArticleHandler/WithoutMatchingKeys (0.00s)
    --- PASS: TestCreateArticleHandler/NilTitleAndContent (0.00s)
    --- PASS: TestCreateArticleHandler/ShortTitle (0.00s)
    --- PASS: TestCreateArticleHandler/ShortContent (0.00s)
    --- PASS: TestCreateArticleHandler/LongTitle (0.00s)
    --- PASS: TestCreateArticleHandler/ValidArticle (0.00s)
PASS
ok      course/article  0.106s
----

Yang kita lakukan sampai saat ini masih berupa __unit test__, yaitu pengetesan untuk satu unit saja.
Dalam hal ini unit yang saya maksud adalah sebuah fungsi. Uji selanjutnya adalah uji end-to-end.
Untuk ini kita bisa melakukan uji manual dengang menggunakan `curl`.

Pertama, kita jalankan dulu server kita seperti kemarin.

[source]
----
> go run .
----

Lalu kita coba membuat satu artikel dengan menggunakan perintah post

[source]
----
> curl --request POST -v \
  --url http://localhost:8000/articles \
  --header 'Content-Type: application/json' \
  --data '{
	"title":"pada hari minggu",
	"content":"pada hari minggu ku turut ayah ke kota, naik delman istimewa ku duduk di muka, 
  ku duduk di samping pak kusir yang sedang bekerja, mengendarai kuda supaya baik jalannya. 
  tuk tik tak tik tuk tik tak tik tuk tik tak tik tuk, tuk tik tak tik tuk tik tak, suara sepatu kuda"
}' <1>

*   Trying 127.0.0.1:8000... 
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /articles HTTP/1.1 <2>
> Host: localhost:8000
> User-Agent: curl/7.78.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 312
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created <3>
< Content-Type: application/json
< Date: Mon, 06 Sep 2021 04:06:37 GMT
< Content-Length: 87
<
{"id":"792d6e31-cbd6-41ee-aca5-646748ebab9e","created_at":"2021-09-06T11:06:37+07:00"} <4>
* Connection #0 to host localhost left intact
----
<1> Cara membuat request JSON dengan `curl`.
<2> Operasi `POST` terlihat karena memakai opsi `-v` yang artinya __verbose__ (dilihatkan semuanya).
<3> Statusnya
<4> __Response Body__ hasil operasi pembuatan artikel.

=== Latihan

. Implementasikan use case dan API __endpoint__ untuk 3 kasus yang lain dari __user story__ di
atas, lengkap dengan kode pengujinya dan perintah `curl` nya.

==== Latihan tingkat lanjut
. Implementasikan kasus penghapusan artikel.
. Implementasikan kasus penghapusan artikel dengan __soft delete__. Artinya tidak
benar-benar hidapus, hanya ditandai kalau artikel yang bersangkutan sudah terhapus.

[TIP]
.Petunjuk pengerjaan
====
. Untuk membaca, metode yang digunakan adalah `GET`. Dalam `chi` ada metode `Get`.
. Jangan lupa baca dokumentasi di https://pkg.go.dev/github.com/go-chi/chi
====
