== Arsitektur Perangkat Lunak

> Good architecture makes the system easy to understand, easy to develop, easy to maintain, and easy
> to deploy. The ultimate goal is to minimize the lifetime cost of the system and to maximize
> programmer productivity. - Robert C Martin

Arsitektur Perangkat Lunak adalah pemahaman bersama tentang desain sebuah sistem. Arsitektur
perangkat lunak menunjukkan penempatan kode di lapisan atau level abstraksi tertentu.

=== Arsitektur 3 tingkat, MVC, Lasagna

Arsitektur 3 tingkat atau __three-tier architecture__ adalah arsitektur yang umum dipakai. Kita
memisahkan lapisan untuk menampilkan (__view__), logika (__logic/controller__), dan penyimpanan
(__storage/model__).

[.float-group]
--
[.left]
.Arsitektur Tiga Tingkat
image::three-tier-arch.svg[3TierArch,450]

Arsitektur ini sangat sederhana dan mudah dipahami. Masalah dari arsitektur ini adalah:
arsitektur ini tidak __spesifik__. Perangkat lunak apapun bisa mengklaim punya arsitektur seperti
ini.

Masalah kedua adalah, tiap lapisan dari arsitektur, **tidak bisa dideploy** secara independen. Untuk
tim yang relatif kecil atau tidak memerlukan __independent deployability__, arsitektur ini cocok
karena mudah dipahami dan koordinasi antar tim bisa dilakukan dengan cepat. Untuk sebuah
organisasi berkembang dan mempunyai __domain__ yang berkembang dan banyak, arsitektur ini akan
merepotkan karena untuk merilis satu fitur, ketiga lapisannya harus diubah, dan bisa jadi
perubahannya perlu koordinasi dengan tim lain. 
--

=== Onion / Heksagonal

Arsitektur __Onion__ atau __Heksagonal__ sedikit berbeda dengan arsitektur tiga tingakt. Arsitektur
tiga tingkat mengklaim bahwa dependensi paling ujung adalah lapisan penyimpanan atau __storage__.
Arsitektur onion dan heksagonal menempatkan __domain__ sebagai lapisan terdalam. Arsitektur ini yang
akan kita pakai di keseluruhan modul training ini.

Bentuk arsitektur onion ini banyak sekali. Robert C Martin (Uncle Bob) mendesain apa yang dia sebut
dengan __Clean Architecture__. Alistair Cockburn dengan __Hexagonal Architecture__.

.Heksagonal dan Onion
image::hexonion.svg[HexaGoninon, 900]

Dalam arsitektur heksagonal atau __onion__ seperti di atas, lapisan terdalam tidak ada pengetahuan
apapun atas lapisan terluarnya. Yang kita kerjakan di <<Dasar Rekayasa Perangkat Lunak>> adalah inti
dari arsitektur ini, yaitu di lapisan entitas, atau sering disebut lapisan domain atau __domain
layer__. Domain layer ini biasanya hanya berupa entitas dan objek saja dan tidak ada konteks maupun
pengetahuan terhadap penyimpanan maupun protokol jaringan.

[NOTE]
.Mengenai jumlah lapisan
====
Jumlah lapisan bisa juga lebih dari yang di gambar. Begitu pula mungkin saja beberapa lapisan
digabungkan atau ditambahkan.
====

=== Lapisan penyimpanan

Lapisan penyimpanan ini adalah lapisan yang menjembatani transfer data dari penyimpanan dan __domain
layer__. Lapisan ini bisa mencari dan menyimpan entitas yang sudah didefinisikan di __domain
layer__. __Pattern__ yang biasa dipakai adalah
https://martinfowler.com/eaaCatalog/repository.html[__Repository Pattern__]. Pola (__pattern__)
memisahkan domain dan kode untuk mengambil entitas berdasarkan kriteria atau predikat tertentu.

Umumnya sebuah __repository__ harus:

. Bisa mencari entitas berdasar kriteria tertentu, misalnya __ID__.
. Bisa menyimpan entitas secara keseluruhan.

==== Implementasi Lapisan Penyimpanan

Selanjutnya, kita akan mengimplementasikan lapisan penyimpanan dengan membuat __in memory store__
atau penyimpanan yang hanya akan menyimpan di dalam memori. Alasan saya memakai ini adalah untuk
menunjukkan bahwa lapisan penyimpanan bisa apa saja, termasuk memori, tidak harus basis data.

[source,go]
.mem_store.go
----
type MemStore struct {
  // .. kita akan mengisi ini nanti
}

// Create A MemStore 

func CreateMemStore() *MemStore {
  return &MemStore{
  }
}
----

===== Membuat Kode Penguji 

Sebelum kita mengisi, kita tulis dulu saja testnya karena kita sudah tahu __behaviour__ yang kita
inginkan yaitu:

. Bisa menyimpan artikel secara keseluruhan 
. Bisa mencari artikel berdasarkan ID dan menampilkan galat jika artikel tidak ada.

[source,go]
.mem_store_test.go
----
include::{sourcedir}/article/mem_store_test.go[]
----
<1> Inisialialisasi penyimpanan dalam memori.
<2> Menyimpan objek `Article`
<3> Mencari objek artikel yang sudah disimpan.
<4> Menguji jika objek artikel tersebut tidak ada.

===== Membuat __Skeleton__ untuk `MemStore`

Kita buat __skeletonnya__ dulu, tapi implementasikan dengan mengimbalikan galat karena belum
terimplementasi dengan mendefinisikan kesalahan pertama yaitu: `ErrNotImplemented` yang berarti
mengembalikan galat bahwa method belum terimplementasi. Kita memakai `context.Context` karena kita
berasumsi bahwa nantinya request ini bisa di-__cancel__.

[source,go,linenums,highlight="1,12-15,16-18"]
.mem_store.go
----
var ErrNotImplemented = errors.New("method not yet implemented")

type MemStore struct {
  
}

func CreateMemStore() *MemStore {
  return &MemStore{
  }
}

func (m *MemStore) FindArticleByID(ctx context.Context, id uuid.UUID) (Article, error) {
  return Article{}, ErrNotImplemented 
}

func (m *MemStore) SaveArticle(ctx context.Context, article Article) error {
  return ErrNotImplemented
}
----

Jika kita jalankan, maka testnya akan gagal karena kita belum berhasil menyimpan

[source]
----
> go test -run TestMemStore .

--- FAIL: TestMemStore (0.00s)
    mem_store_test.go:22:
                Error Trace:    mem_store_test.go:22
                Error:          Received unexpected error:
                                method not yet implemented
                Test:           TestMemStore
FAIL
FAIL    course/article  0.370s
FAIL
----

===== Mengimplementasikan Penyimpanan Dengan Menggunakan Map

Ada beberapa cara mengimplementasikan memory store ini. Bisa dengan list atau map. Kita akan memakai
map untuk keperluan kali ini. Karena map dalam go itu tidak __atomic__, kita perlu menambahkan
`*sync.RWLock` untuk menjaga konsistensi map dan menghindari __data race__.

[source,go]
.mem_store.go
----
type MemStore struct {
  articles	map[uuid.UUID]Article

  lock *sync.RWMutex
}
----

Kita implementasikan dahulu metode `SaveArticle`. Karena ini map, akan sangat kecil kemungkinan
gagal.

[source,go,linenums]
.mem_store.go
----

var (
  ErrNilArticle = errors.New("cannot save nil article")
)

func CreateMemStore() *MemStore {
  return MemStore{
    articles: make(map[uuid.UUID]Article),
    lock: &sync.RWMutex{},
  }
}

func (s *MemStore) SaveArticle(ctx context.Context, article Article) error {
  s.Lock()
  defer s.Unlock()

  if article.IsNil() {
    return ErrNilArticle
  }

  articles[article.ID] = article 

  return nil
}
 
----

Kita jalanan lagi testnya, dan masih gagal. Tapi pindah ke baris 25. Baris ini adalah metode untuk
mencari artikel berdasarkan ID.

[source]
----
> go run -run TestMemStore .

--- FAIL: TestMemStore (0.00s)
    mem_store_test.go:25:
                Error Trace:    mem_store_test.go:25
                Error:          Received unexpected error:
                                method not yet implemented
                Test:           TestMemStore
FAIL
FAIL    course/article  0.349s
FAIL
----

===== Mengimplementasikan `FindArticleByID`

Selanjutnya kita implementasikan `FindArticleByID`. Ada satu galat yang kita definisikan terlebih
dahulu yaitu galat di mana ketika artikel tidak ditemukan.

[source,go,linenums]
.mem_store.go
----

var ErrArticleNotFound = errors.New("article not found")

func (s *MemStore) FindArticleByID(ctx context.Context, id uuid.UUID) (Article, error) {
  s.lock.RLock()
  defer s.lock.RUnlock()

  article, ok := s.articles[id] 

  if !ok {
    return Article{}, ErrArticleNotFound
  }

  return article, nil
}

----

Dengan diimplementasikan kedua metode di atas maka, implementasi penyimpanan dengan map kita sudah
selesai. Kode lengkapnya seperti ini:

[source,go,linenums]
.mem_store.go 
----
include::{sourcedir}/article/mem_store.go[]
----


=== Latihan

. Buatlah implementasi MemStore di atas dengan menggunakan Slice. **Petunjuk:** hati-hati dengan
duplikasi ID ketika menyimpan.
